- hosts: workstation
  gather_facts: false
  roles:
  - name: osp-facts
  tasks:
  
  - name: Curl website
    uri:
      url: "http://{{ item }}"
      return_content: yes
    loop: '{{ groups.frontends }}'
    register: webpage
    until: webpage.status == "200"
    retries: 15
    delay: 2
    tags:
      - osp.smoke
        
  - debug: var=webpage.content

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].content"
    tags:
      - osp.smoke
