---
# defaults file for osp-servers

cloud_name: openstack
osp_networks:
  - name: ext_network
    external: true
    subnet:
      name: ext_subnet
      cidr: '192.0.2.0/24'
      allocation_pool_start: '192.0.2.150'
      allocation_pool_end: '192.0.2.200'
      enable_dhcp: no
      dns_nameservers:
        - '8.8.8.8'
      host_routes:
        - destination: '0.0.0.0/0'
          nexthop: '192.0.2.254'
  - name: int_network
    external: false
    subnet:
      name: int_subnet
      cidr: '172.16.0.0/24'
      dns_nameservers:
        - '8.8.8.8'
osp_routers:
  - name: router
    network: ext_network
    external_fixed_ips:
      subnet: ext_subnet
    interfaces:
      - int_subnet
osp_securitygroups:
  - name: apps
    rules:
      - protocol: tcp
        port_range_min: '22'
        port_range_max: '22'
        remote_ip_prefix: '0.0.0.0/0'
      - protocol: tcp
        port_range_min: '8080'
        port_range_max: '8080'
        remote_ip_prefix: '0.0.0.0/0'
  - name: frontend
    rules:
      - protocol: tcp
        port_range_min: '22'
        port_range_max: '22'
        remote_ip_prefix: '0.0.0.0/0'
      - protocol: tcp
        port_range_min: '80'
        port_range_max: '80'
        remote_ip_prefix: '0.0.0.0/0'
      - protocol: tcp
        port_range_min: '443'
        port_range_max: '443'
        remote_ip_prefix: '0.0.0.0/0'
  - name: db
    rules:
      - protocol: tcp
        port_range_min: '22'
        port_range_max: '22'
        remote_ip_prefix: '0.0.0.0/0'
      - protocol: tcp
        port_range_min: '5432'
        port_range_max: '5432'
        remote_ip_prefix: '0.0.0.0/0'
osp_flavors:
  m1.medium:
    state: present
    ram: '2048'
    vcpus: '1'
    disk: '20'
