---
- os_network:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ item.name }}"
    external: "{{ item.external }}"
    provider_network_type: "{{ item.provider_network_type }}"
    provider_physical_network: "{{ item.provider_physical_network }}"
  loop:
    - "{{ osp_networks }}"
- os_subnet:
    cloud: "{{ cloud_name }}"
    state: present
    network_name: "{{ item.0.name }}"
    name: "{{ item.0.subnet.name }}"
    cidr: "{{ item.0.subnet.cidr }}"
    allocation_pool_start: "{{ item.0.subnet.allocation_pool_start }}"
    allocation_pool_end: "{{ item.0.subnet.allocation_pool_end }}"
    enable_dhcp: "{{ item.0.subnet.enable_dhcp }}"
    dns_nameservers:
      - "{{ item.0.subnet.dns_nameservers.0 }}"
    host_routes:
      - destination: "{{ item.1.destination }}"
        nexthop: "{{ item.1.nexthop }}"
  loop:
    - "{{ osp_networks }}"
    - subnet.host_routes
- os_router:
    cloud: "{{ cloud_name }}"
    state: present
    name: "{{ item.0.name }}"
    network: "{{ item.0.network }}"
    external_fixed_ips:
      - subnet: "{{ item.0.external_fixed_ips.subnet }}"
    interfaces:
      - "{{ item.1 }}"
  loop:
    - "{{ osp_routers }}"
    - interfaces
